apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
  - repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 8.0.1
    helm:
      valueFiles:
        - $values/manifests/nextcloud/values.yaml
  - repoURL: https://github.com/t-tibor/HomeLabArgoCD.git
    targetRevision: main
    path: manifests/nextcloud
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
