apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-observability
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://github.com/prometheus-community/helm-charts/
    targetRevision: kube-prometheus-stack-55.5.0
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Automatically creates the 'monitoring' namespace if it doesn't exist
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd